#pragma once

#define DMDCOMMON_VERSION_MAJOR 0 // X Digits
#define DMDCOMMON_VERSION_MINOR 1  // Max 2 Digits
#define DMDCOMMON_VERSION_PATCH 0  // Max 2 Digits

#define _DMDCOMMON_STR(x)    #x
#define DMDCOMMON_STR(x)     _DMDCOMMON_STR(x)

#define DMDCOMMON_VERSION DMDCOMMON_STR(DMDCOMMON_VERSION_MAJOR) "." DMDCOMMON_STR(DMDCOMMON_VERSION_MINOR) "." DMDCOMMON_STR(DMDCOMMON_VERSION_PATCH)
#define DMDCOMMON_MINOR_VERSION DMDCOMMON_STR(DMDCOMMON_VERSION_MAJOR) "." DMDCOMMON_STR(DMDCOMMON_VERSION_MINOR)
